apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: pearlchain-poc
  name: pearlchain-poc
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: pearlchain-poc
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: pearlchain-poc
    spec:
      containers:
      - image: us.icr.io/gs_dev_ns/pearlchaindbm:v1.1
        imagePullPolicy: Always
        name: pearlchain-poc
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        args: ["--spring.application.json=$(BINDING)"]
        env:
        - name: BINDING
          valueFrom:
            secretKeyRef:
              name: binding-storm-tracker-postgresql-db
              key: binding
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
